# Generated by Django 5.2.1 on 2025-05-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='stripe_payment_intent',
        ),
        migrations.AddField(
            model_name='donation',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(choices=[('money', 'Money'), ('goods', 'Goods')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='logistics_type',
            field=models.CharField(blank=True, choices=[('pickup', 'Pickup from donor'), ('delivery', 'Donor will deliver')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='pickup_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
