# Generated by Django 5.2.1 on 2025-05-16 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0002_remove_donation_stripe_payment_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='donation',
            name='contact_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='item_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
