# Generated by Django 5.2.1 on 2025-05-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0003_remove_donation_quantity_donation_contact_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='pickup_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
