# Generated by Django 5.2.1 on 2025-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0004_alter_donation_pickup_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='contact_info',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
