# Generated by Django 5.2.1 on 2025-05-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Donors', '0005_alter_donation_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
