# Generated by Django 5.2 on 2025-05-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('shelter', 'Shelter'), ('medical', 'Medical Supplies'), ('water', 'Clean Water'), ('other', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(default='Available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
