# Generated by Django 5.2.1 on 2025-05-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_skill', to='core.skill'),
        ),
    ]
