# Generated by Django 5.2.1 on 2025-05-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_task_relief_request_alter_task_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteersRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('food', 'Food'), ('shelter', 'Shelter'), ('medical', 'Medical Supplies'), ('water', 'Clean Water'), ('other', 'Other')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approve', 'Approve'), ('reject', 'Reject')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='volunteers_requests', to='Task.task')),
            ],
        ),
    ]
