# Generated by Django 5.2.1 on 2025-05-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0002_event_reliefrequest_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefrequest',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
