# Generated by Django 5.2.1 on 2025-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0003_reliefrequest_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('pandemic', 'Pandemic')], default='flood', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='specific_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
