# Generated by Django 5.2.1 on 2025-05-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0004_event_event_type_event_specific_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(default='#FF0000', max_length=7),
        ),
        migrations.AddField(
            model_name='event',
            name='intensity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=20),
        ),
    ]
