# Generated by Django 5.2.1 on 2025-05-21 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0007_alter_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectedPeopleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='affected_people_images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
