# Generated by Django 5.2.1 on 2025-05-21 16:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0008_affectedpeopleimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectedpeopleimages',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
