# Generated by Django 5.2.1 on 2025-05-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Affected', '0009_affectedpeopleimages_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectedpeopleimages',
            name='event_type',
            field=models.CharField(choices=[('flood', 'Flood'), ('fire', 'Fire'), ('earthquake', 'Earthquake'), ('pandemic', 'Pandemic')], default='flood', max_length=20),
        ),
    ]
